displayName=OmniPresence
author=OmniPresence
description=Reports your OSRS activity to OmniPresence for Discord Rich Presence
tags=discord,rich presence,status,activity
version=1.0.0
hasRedirect=false
